apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-dump-server-deployment
  labels:
    app: simple-dump-server
    heritage: {{.Release.Service | quote}}
    release: {{.Release.Name | quote}}
    chart: {{ .Chart.Name }}
  annotations:
    "service-version": {{ .Chart.AppVersion | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: simple-dump-server
  template:
    metadata:
      labels:
        heritage: {{.Release.Service | quote}}
        release: {{.Release.Name | quote}}
        chart: {{ .Chart.Name }}
        app: simple-dump-server
    spec:
      serviceAccountName: simple-dump-server
      containers:
        - name: {{ .Chart.Name }}
          #securityContext:
          image: {{required ".Values.image.source is required" .Values.image.source }} # check this value
          imagePullPolicy: {{ .Values.image.pullPolicy }} #check this value       
          ports:
            - name: http
              containerPort: 8080 #check
              protocol: TCP
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 10      
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            # periodSeconds: 30
            timeoutSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 10 }}
      restartPolicy: Always #check
      terminationGracePeriodSeconds: 30 #check
      dnsPolicy: ClusterFirst #check
      securityContext: {}